### ISSUE TITLE
Restack tracking issue

### ISSUE THREAD

**Issue by 9999years** [9999years/git-gr#50]
`restack` works at least mostly but needs a bunch of fixes. Let's track them all here.

- [ ] Do not restack abandoned changes. #48
- [ ] Restore the previously checked out change after restacking. #44 
- [ ] Unify `restack this` and `restack`. #36 
- [ ] Cope with the user running `git cherry-pick --continue` themselves. #35
- [ ] Use rebases instead of cherry-picks. #49
- [ ] When displaying the tree of changes, indicate which changes are out-of-date. #33
- [ ] Show steps to be performed. #34
